server:
  port: 8899
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/system?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
    one:
      max-active: 10
      max-wait: 10000
    two:
      max-active: 20
      max-wait: 20000
  redis:
    host: localhost
    port: 4379
    password: root
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  output:
    ansi:
      enabled: always
#出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
#不要为工程中的资源文件建立映射
  resources:
    add-mappings: false
logging:
  level:
    com: debug
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
mapper:
    mappers:
        - com.basicfu.system.common.CustomMapper
    not-empty: false
    identity: MYSQL